### ISSUE TITLE
Guide for git use?

### ISSUE THREAD

**Issue by drewdotpro** [martin-lizner/trezor-ssh-agent#12]
Your README says this is for 
```
apps like Putty, WinSCP or other Pageant-compatible clients (e.g. git)
```

My only interest is using this as a way to access my git repositories, but the readme only covered Putty.

Is there a guide for using this app with git (which I use inside Git Bash), or am I missing something?

Thanks

**Comment by drewdotpro** [comment]
Solved

1) Follow the PuTTY setup guide in the readme

2) Add your public key to github/gitlab etc

3) Add env var `GIT_SSH` as `C:\Program Files (x86)\PuTTY\plink.exe` (or whatever yours might be)

4) Go to the folder where plink is and execute `plink git@github.com` (or gitlab etc) it should log in. 

5) You can now `git pull` etc as you would usually.

**Comment by martin-lizner** [comment]
Good that you figured it out :-) My app behaves just like Pageant from other apps perspective. So anything that works with Putty Pageant should work with my agent too.
