### ISSUE TITLE
Cannot detect KeepKey after firmware update

### ISSUE THREAD

**Issue by NTICompass** [martin-lizner/trezor-ssh-agent#14]
I have a KeepKey and I was on firmware 5.10.2 and it was working with the agent for SSH.

I was curious about updating the KeepKey firmware, but I was worried about losing SSH support.  I decided to upgrade to 6.4.0, and unfortunately SSH is not working anymore.

When I use the agent in Windows, I get the following error in the log:
```
WARNING: KeepKey not ready.
```

It seems the new upgrade may've changed the device's USB ID, or something like that.  Is this is an issue with the KeepKey firmware or with the agent?  Is this related to Issue #13 ?

**Comment by NTICompass** [comment]
This is the same issue as https://github.com/romanz/trezor-agent/pull/318

**Comment by martin-lizner** [comment]
Hi, Im deeply sorry but Im unable to support newer firmwares of the devices since I rely on [Java API](https://github.com/gary-rowe/trezor-java) that is not maintained either :-(

**Comment by NTICompass** [comment]
That's ok.  The issue seems to be that the new KeepKey firmware is using WebUSB (not USB HID).  The python-keepkey lib has this support, but I'm not sure about the Java lib.
