### ISSUE TITLE
Unfork from multibit-hardware repo

### ISSUE THREAD

**Issue by prusnak** [martin-lizner/trezor-ssh-agent#3]
Github treats this repo as if it was a fork of multibit-hardware repo. This creates a few problems. Forked repositories cannot be searched and have several other disadvantages.

I am not aware of other way of unforking than just deleting the repo, creating a new one with the same name and pushing back the git contents.

**Comment by martin-lizner** [comment]
I made fork from courtesy to MultBit for providing API. Didnt have clue that it can cause troubles, I asked github support for defork. Thanks for pointing this out.

**Comment by martin-lizner** [comment]
Done.
