### ISSUE TITLE
Can the Trezor be put to sleep after a certain timeout?

### ISSUE THREAD

**Issue by ghost** [martin-lizner/trezor-ssh-agent#5]
If I leave my Trezor plugged in while the agent is running, the screen stays on. Could it somehow blank the screen/turn it off after a while so we don't risk burn-in when leaving the Trezor connected for extended periods of time?

**Comment by martin-lizner** [comment]
Hi, good idea. I can use client.clearSession() for that. It makes device forget cached PIN and passphrase. Im thinking of having timeout user configurable in property file, which Im already introducing in new app version (currently keepkey branch). I would probably count timeout from last operation happening on the device, what default timeout would you consider convenient? M.

**Comment by martin-lizner** [comment]
Feature implemented and released in 1.0.2 version.
