### ISSUE TITLE
Possible update required

### ISSUE THREAD

**Issue by livegnik** [martin-lizner/trezor-ssh-agent#6]
Your solution seems like the only relatively simple Windows solution out there, re: SSH and Windows, but now that trezord is obsolete, and the tray icon is no longer there on the taskbar, I wonder what the easiest solution is to display the pubkey on a Windows machine.

The Trezor Wallet app allows me to sign and verify messages, but I don't see a way to display the pubkey there, apart from the Bitcoin addresses. I would love to follow your manual and try it out for myself, but I'm not sure how to retrieve the pubkey on this box at the moment.

Am I making a user boo boo, or could the readme use an update? If it's the latter, feel free to let me know if there's anything I can do to help.

**Comment by martin-lizner** [comment]
Hi and thanks for the note! My application should still work fine as far as I know. It works in simillar fashion as e.g. Pageant (Putty SSH Agent). Its not related to Trezor Wallet in any way, so you need to install it (binary is provided [here](https://github.com/martin-lizner/trezor-ssh-agent/releases/download/v1.0.3/TrezorSSHAgent.exe)) as Windows application. In fact, your Trezor web wallet should not be running simultaneously else Trezor SSH Agent will not see device ready. Hope this clear things out.

**Comment by livegnik** [comment]
You are right, and I can confirm it's working. Sorry for taking your time, and thanks for the fast response!
