### ISSUE TITLE
WARNING: Trezor not ready after show public key command

### ISSUE THREAD

**Issue by marekbatelka** [martin-lizner/trezor-ssh-agent#7]
Hi Martin,
I've downloaded trezor-ssh-agent v 1.0.3 running on Windows 10 64b.
**Trezor T** connected, PIN provided.
When I run agent, it appears as tray icon. 

**Observation:**
I click Show public key and nothing happens. (NOK)

**Expected:** 
Show key for copy paste.

I tried to close chrome, reconnect device, restart PC.

This is what log shows:

> [22.04.2018 16:44:30] INFO: Java version: 1.8.0_91-b15 (64-bit)
> [22.04.2018 16:44:30] INFO: Java home: C:\Program Files\Java\jre1.8.0_91
> [22.04.2018 16:44:30] INFO: Trezor SSH Agent 1.0.3 started successfully
> [22.04.2018 16:44:30] INFO: Existing settings file loaded: C:\Users\e558972\Trezor_Agent.properties
> [22.04.2018 16:44:30] INFO: Trezor Service Started
> [22.04.2018 16:44:31] INFO: Received USB event: SHOW_DEVICE_DETACHED
> [22.04.2018 16:45:11] INFO: Java version: 1.8.0_91-b15 (64-bit)
> [22.04.2018 16:45:11] INFO: Java home: C:\Program Files\Java\jre1.8.0_91
> [22.04.2018 16:45:11] INFO: Trezor SSH Agent 1.0.3 started successfully
> [22.04.2018 16:45:11] INFO: Existing settings file loaded: C:\Users\e558972\Trezor_Agent.properties
> [22.04.2018 16:45:11] INFO: Trezor Service Started
> [22.04.2018 16:45:12] INFO: Received USB event: SHOW_DEVICE_DETACHED
> [22.04.2018 16:45:39] INFO: Request for operation: SSH2_AGENT_GET_IDENTITIES
> [22.04.2018 16:45:39] WARNING: Trezor not ready.
> [22.04.2018 16:45:55] INFO: Request for operation: SSH2_AGENT_GET_IDENTITIES
> [22.04.2018 16:45:55] WARNING: Trezor not ready.

**Comment by martin-lizner** [comment]
Hi, thanks for trying out my app! Trezor T is not currently supported, but will be soon. Stay tuned. M.

**Comment by marekbatelka** [comment]
ahh, that´s why,
didn´t know, tuning in progress. 
Let me know if testing needed.
Díky!

**Comment by elcomtik** [comment]
i have same problem , i started to use model T and really missing this feature in your windows agent. I might be able to help with development

**Comment by Senjuu** [comment]
I recently got the same problem. After I updated the firmware of my Trezor ONE today. Now I always get the "Trezor not ready" when I click on "Show Public Key" or connect in putty in the log.

**Comment by Senjuu** [comment]
I recently got the same problem. I updated the firmware of my Trezor ONE today. Now I always get the "Trezor not ready" when I click on "Show Public Key" or connect in putty in the log.

**Comment by godofrefuse** [comment]
> Hi, thanks for trying out my app! Trezor T is not currently supported, but will be soon. Stay tuned. M.

Is model T supported yet?
